### ISSUE TITLE
After first payment a second scan doesn't work

### ISSUE THREAD

**Issue by Perlover** [hsjoberg/blixt-wallet#175]
If i do scan and pay then a second scanning - there nothing happens. I see camera view but if i scan qr code - it's not scanned. If i click Back button and run again - there is same thing. But if i kill application and run again - i can scan once invoice. Second and so on scanning doesn't work again

**Comment by hsjoberg** [comment]
Thanks for the bug report.
I am unable to replicate the issue myself on my phone(s), I'll try to find if something is wrong.

**Comment by Perlover** [comment]
I noticed more: an any main function works only once and for next successful working i was needed to kill application and start again (Android 10, Samsung Note 9)

For example these functions:

1. Scan and send
2. Receive button (infinitive loading button at bottom of page)

May be it was related with fingerprint / PIN page - they are asked only during a first start and after killing.

**Comment by hsjoberg** [comment]
Hmm it sounds like lnd is crashing, which will make the frontend unresponsive.
So after a successful send, you are unable to do anything else (send, receive etc)?

> May be it was related with fingerprint / PIN page - they (fingerprint and PIN) are asked only during a first start and after killing. If i exit from application by Android Back button and start again i see wallet without fingerprint authorization but and a other functions don't work after this

About moving into the app after backing without authorization is expected behavior for the moment being. I wonder if your phone is killing the lnd process when you're moving back. Do you the syncing icon as well after moving back?

> (Android 10, Samsung Note 9)

Thanks for telling me the device
